/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafos_jair2;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PERSONAL
 */
public class interfase extends javax.swing.JFrame {

    /**
     * Creates new form interfase
     */
    DatosEstacion datosEstacion;
    
 
      public interfase() {
        datosEstacion=new DatosEstacion(11);
        datosEstacion.getGrafo().addAdyacencia(0, 2);
        datosEstacion.getGrafo().addAdyacencia(1,7);
        datosEstacion.getGrafo().addAdyacencia(1, 10);
        datosEstacion.getGrafo().addAdyacencia(2, 3);
        datosEstacion.getGrafo().addAdyacencia(2, 7);
        datosEstacion.getGrafo().addAdyacencia(2, 8);
        datosEstacion.getGrafo().addAdyacencia(3, 4);
        datosEstacion.getGrafo().addAdyacencia(3, 6);
        datosEstacion.getGrafo().addAdyacencia(4, 5);
        datosEstacion.getGrafo().addAdyacencia(5, 9);
        datosEstacion.getGrafo().addAdyacencia(6, 7);
        datosEstacion.getGrafo().addAdyacencia(6, 8);
        datosEstacion.getGrafo().addAdyacencia(7, 10);
        datosEstacion.getGrafo().addAdyacencia(8, 10);
        
         datosEstacion.getGrafo().addMaterial(0,0);
       datosEstacion.getGrafo().addMaterial(1,100);
       datosEstacion.getGrafo().addMaterial(2, 250);
       datosEstacion.getGrafo().addMaterial(3, 300);
       datosEstacion.getGrafo().addMaterial(4, 200);
       datosEstacion.getGrafo().addMaterial(5, 50);
       datosEstacion.getGrafo().addMaterial(6, 20);
       datosEstacion.getGrafo().addMaterial(7, 50);
       datosEstacion.getGrafo().addMaterial(8, 400);
       datosEstacion.getGrafo().addMaterial(9, 300);
       datosEstacion.getGrafo().addMaterial(10, 800);
        /*
      
         */
        
        initComponents();
        lienzo11.setDatosEstacion(datosEstacion);
        TextoRuta.setEditable(false);
        TextoNuevaCantidadMaterial.setEditable(false);
        TextoEstacion.setEditable(false);
        botonModificarMaterial.setEnabled(false);
        TextoEstacion1.setEditable(false);
        TextoEstacion2.setEditable(false);
        botonAgregarAdy.setEnabled(false);
        botonQuitarAdy.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo11 = new grafos_jair2.Lienzo1();
        TextoRuta = new javax.swing.JTextField();
        TextoCantidadCamion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonRuta = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonDecision = new java.awt.Button();
        botonModificarMaterial = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextoNuevaCantidadMaterial = new javax.swing.JTextField();
        TextoEstacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonDecision2 = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextoEstacion1 = new javax.swing.JTextField();
        TextoEstacion2 = new javax.swing.JTextField();
        botonQuitarAdy = new java.awt.Button();
        botonAgregarAdy = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzo11Layout = new javax.swing.GroupLayout(lienzo11);
        lienzo11.setLayout(lienzo11Layout);
        lienzo11Layout.setHorizontalGroup(
            lienzo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        lienzo11Layout.setVerticalGroup(
            lienzo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        TextoCantidadCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCantidadCamionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel1.setText("Cantidad inicial Material camión ");

        jLabel2.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel2.setText("Ruta de recorrido de camión");

        BotonRuta.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        BotonRuta.setLabel("Obtener Ruta");
        BotonRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRutaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel3.setText("¿Desea Modificar alguna cantidad");

        jLabel4.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel4.setText("de material en una estación?");

        botonDecision.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        botonDecision.setLabel("SI");
        botonDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDecisionActionPerformed(evt);
            }
        });

        botonModificarMaterial.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        botonModificarMaterial.setLabel("Modificar");
        botonModificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarMaterialActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel6.setText("Estación");

        TextoNuevaCantidadMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNuevaCantidadMaterialActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel7.setText("El presente programa tiene los valores");

        jLabel8.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel8.setText("de materiales de cada estacion por ");

        jLabel9.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel9.setText("defecto (dados en el parcial), asi como");

        jLabel10.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel10.setText("las respectivas adyacencias.");

        jLabel11.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel11.setText("¿Desea Modificar alguna adyacencia");

        jLabel12.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel12.setText("del grafo representado?");

        botonDecision2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        botonDecision2.setLabel("SI");

        jLabel13.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel13.setText("Estacion 1");

        jLabel14.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        jLabel14.setText("Estacion 2");

        TextoEstacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEstacion1ActionPerformed(evt);
            }
        });

        botonQuitarAdy.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        botonQuitarAdy.setLabel("Quitar");

        botonAgregarAdy.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        botonAgregarAdy.setLabel("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lienzo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextoNuevaCantidadMaterial))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoEstacion2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoEstacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonQuitarAdy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(botonAgregarAdy, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(botonModificarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(botonDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(botonDecision2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoCantidadCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(BotonRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextoNuevaCantidadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDecision2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TextoEstacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TextoEstacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonQuitarAdy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarAdy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lienzo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCantidadCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoCantidadCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCantidadCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCantidadCamionActionPerformed

    private void BotonRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRutaActionPerformed
        try {
            // TODO add your handling code here:
            TextoRuta.setText("");
            datosEstacion.getGrafo().setValorCamion(Integer.parseInt(TextoCantidadCamion.getText()));
            datosEstacion.getGrafo().mostrarRuta();
            TextoRuta.setText(datosEstacion.getGrafo().ruta.toString());
        } catch (Exception ex) {
            Logger.getLogger(interfase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonRutaActionPerformed

    private void TextoEstacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEstacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEstacion1ActionPerformed

    private void TextoNuevaCantidadMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNuevaCantidadMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNuevaCantidadMaterialActionPerformed

    private void botonDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDecisionActionPerformed
        // TODO add your handling code here:
        botonModificarMaterial.setEnabled(true);
        TextoEstacion.setEditable(true);
        TextoNuevaCantidadMaterial.setEditable(true);
        
    }//GEN-LAST:event_botonDecisionActionPerformed

    private void botonModificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarMaterialActionPerformed
        // TODO add your handling code here:
        datosEstacion.getGrafo().cambiarMaterial(Integer.parseInt(TextoEstacion.getText()),Integer.parseInt(TextoNuevaCantidadMaterial.getText()));
    }//GEN-LAST:event_botonModificarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BotonRuta;
    private javax.swing.JTextField TextoCantidadCamion;
    private javax.swing.JTextField TextoEstacion;
    private javax.swing.JTextField TextoEstacion1;
    private javax.swing.JTextField TextoEstacion2;
    private javax.swing.JTextField TextoNuevaCantidadMaterial;
    private javax.swing.JTextField TextoRuta;
    private java.awt.Button botonAgregarAdy;
    private java.awt.Button botonDecision;
    private java.awt.Button botonDecision2;
    private java.awt.Button botonModificarMaterial;
    private java.awt.Button botonQuitarAdy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private grafos_jair2.Lienzo1 lienzo11;
    // End of variables declaration//GEN-END:variables
}
